import 'dart:async';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sales_sphere/features/catalog/models/catalog.models.dart';

part 'catalog_item_details.vm.g.dart';

// --- Provider to fetch a SINGLE item's details ---
@riverpod
Future<CatalogItem> catalogItemDetails(
    Ref ref, // This type will be generated
    String itemId,
    ) async {

  // This provider will fetch and return a single item.
  try {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 700));

    // Get the mock data
    final mockItems = _getMockItemDetails();

    // Find the item or throw an error
    final item = mockItems.firstWhere(
          (i) => i.id == itemId,
      orElse: () => throw Exception('Item with ID $itemId not found'),
    );
    return item;
  } catch (e) {
    // Error is already re-thrown, logging handled by provider observer
    rethrow;
  }
}

// --- Mock Data ---
// This is a private helper function to hold the detailed mock data
List<CatalogItem> _getMockItemDetails() {
  return [
    // Marble Category (7 items)
    const CatalogItem(
      id: '101',
      name: 'Italian White Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Premium',
      sku: 'MAR-001',
      imageAssetPath: 'assets/images/products/marble_white.jpg',
      price: 450.0,
      material: 'Natural Stone',
      origin: 'Italy',
      finish: 'Polished',
      application: 'Floor/Wall',
      durability: 'High',
      inStockSqFt: 4800,
    ),
    const CatalogItem(
      id: '102',
      name: 'Carrara Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Classic',
      sku: 'MAR-002',
      imageAssetPath: 'assets/images/products/marble_carrara.jpg',
      price: 380.0,
      material: 'Natural Stone',
      origin: 'Italy',
      finish: 'Honed',
      application: 'Floor/Wall',
      durability: 'High',
      inStockSqFt: 3400,
    ),
    const CatalogItem(
      id: '103',
      name: 'Black Galaxy Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Exotic',
      sku: 'MAR-003',
      imageAssetPath: 'assets/images/products/marble_black.jpg',
      price: 520.0,
      material: 'Natural Stone',
      origin: 'India',
      finish: 'Polished',
      application: 'Floor/Wall/Countertop',
      durability: 'Very High',
      inStockSqFt: 2600,
    ),
    const CatalogItem(
      id: '104',
      name: 'Statuario Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Luxury',
      sku: 'MAR-004',
      imageAssetPath: 'assets/images/products/marble_statuario.jpg',
      price: 680.0,
      material: 'Natural Stone',
      origin: 'Italy',
      finish: 'Polished',
      application: 'Wall/Countertop',
      durability: 'High',
      inStockSqFt: 1800,
    ),
    const CatalogItem(
      id: '105',
      name: 'Emperador Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Brown',
      sku: 'MAR-005',
      imageAssetPath: 'assets/images/products/marble_emperador.jpg',
      price: 420.0,
      material: 'Natural Stone',
      origin: 'Spain',
      finish: 'Polished',
      application: 'Floor/Wall',
      durability: 'High',
      inStockSqFt: 3800,
    ),
    const CatalogItem(
      id: '106',
      name: 'Crema Marfil Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Beige',
      sku: 'MAR-006',
      imageAssetPath: 'assets/images/products/marble_crema.jpg',
      price: 390.0,
      material: 'Natural Stone',
      origin: 'Spain',
      finish: 'Polished',
      application: 'Floor/Wall',
      durability: 'Medium-High',
      inStockSqFt: 4400,
    ),
    const CatalogItem(
      id: '107',
      name: 'Green Marble',
      categoryId: '1',
      categoryName: 'Marble',
      subCategory: 'Exotic',
      sku: 'MAR-007',
      imageAssetPath: 'assets/images/products/marble_green.jpg',
      price: 550.0,
      material: 'Natural Stone',
      origin: 'India',
      finish: 'Polished',
      application: 'Floor/Wall',
      durability: 'High',
      inStockSqFt: 3000,
    ),

    // Paints Category (7 items)
    const CatalogItem(
      id: '201',
      name: 'Asian Paints Royale',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Premium',
      sku: 'PAI-001',
      imageAssetPath: 'assets/images/products/paint_royale.jpg',
      price: 850.0,
      material: 'Acrylic Emulsion',
      origin: 'India',
      finish: 'Smooth Matte',
      application: 'Interior Walls',
      durability: 'Excellent Washability',
      inStockSqFt: 8000,
    ),
    const CatalogItem(
      id: '202',
      name: 'Berger Easy Clean',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Interior',
      sku: 'PAI-002',
      imageAssetPath: 'assets/images/products/paint_berger.jpg',
      price: 720.0,
      material: 'Acrylic Emulsion',
      origin: 'India',
      finish: 'Smooth',
      application: 'Interior Walls',
      durability: 'Good Washability',
      inStockSqFt: 6000,
    ),
    const CatalogItem(
      id: '203',
      name: 'Nerolac Excel',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Interior',
      sku: 'PAI-003',
      imageAssetPath: 'assets/images/products/paint_nerolac.jpg',
      price: 680.0,
      material: 'Acrylic Emulsion',
      origin: 'India',
      finish: 'Smooth',
      application: 'Interior Walls',
      durability: 'Good',
      inStockSqFt: 7200,
    ),
    const CatalogItem(
      id: '204',
      name: 'Dulux Weathershield',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Exterior',
      sku: 'PAI-004',
      imageAssetPath: 'assets/images/products/paint_dulux.jpg',
      price: 920.0,
      material: '100% Acrylic',
      origin: 'India',
      finish: 'Weather Resistant',
      application: 'Exterior Walls',
      durability: 'Very High (UV Protected)',
      inStockSqFt: 5200,
    ),
    const CatalogItem(
      id: '205',
      name: 'Asian Paints Apcolite',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Emulsion',
      sku: 'PAI-005',
      imageAssetPath: 'assets/images/products/paint_apcolite.jpg',
      price: 780.0,
      material: 'Acrylic Emulsion',
      origin: 'India',
      finish: 'Smooth Matte',
      application: 'Interior Walls',
      durability: 'Excellent',
      inStockSqFt: 6600,
    ),
    const CatalogItem(
      id: '206',
      name: 'Berger Weather Coat',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Exterior',
      sku: 'PAI-006',
      imageAssetPath: 'assets/images/products/paint_weathercoat.jpg',
      price: 890.0,
      material: '100% Acrylic',
      origin: 'India',
      finish: 'Weather Resistant',
      application: 'Exterior Walls',
      durability: 'High (All Weather)',
      inStockSqFt: 5600,
    ),
    const CatalogItem(
      id: '207',
      name: 'Nerolac Impressions',
      categoryId: '2',
      categoryName: 'Paints',
      subCategory: 'Designer',
      sku: 'PAI-007',
      imageAssetPath: 'assets/images/products/paint_impressions.jpg',
      price: 950.0,
      material: 'Premium Acrylic',
      origin: 'India',
      finish: 'Textured/Metallic',
      application: 'Interior Feature Walls',
      durability: 'Very High',
      inStockSqFt: 4800,
    ),

    // Sanitary Category (7 items)
    const CatalogItem(
      id: '301',
      name: 'Hindware Wash Basin',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Basin',
      sku: 'SAN-001',
      imageAssetPath: 'assets/images/products/sanitary_basin.jpg',
      price: 3200.0,
      material: 'Ceramic',
      origin: 'India',
      finish: 'Glossy White',
      application: 'Bathroom',
      durability: 'High',
      inStockSqFt: 45,
    ),
    const CatalogItem(
      id: '302',
      name: 'Parryware Toilet Seat',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Toilet',
      sku: 'SAN-002',
      imageAssetPath: 'assets/images/products/sanitary_toilet.jpg',
      price: 4500.0,
      material: 'Ceramic',
      origin: 'India',
      finish: 'Glossy White',
      application: 'Bathroom',
      durability: 'Very High',
      inStockSqFt: 35,
    ),
    const CatalogItem(
      id: '303',
      name: 'Jaquar Shower',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Shower',
      sku: 'SAN-003',
      imageAssetPath: 'assets/images/products/sanitary_shower.jpg',
      price: 2800.0,
      material: 'Stainless Steel',
      origin: 'India',
      finish: 'Chrome Plated',
      application: 'Bathroom',
      durability: 'High',
      inStockSqFt: 60,
    ),
    const CatalogItem(
      id: '304',
      name: 'Cera Faucet',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Faucet',
      sku: 'SAN-004',
      imageAssetPath: 'assets/images/products/sanitary_faucet.jpg',
      price: 1500.0,
      material: 'Brass',
      origin: 'India',
      finish: 'Chrome Plated',
      application: 'Bathroom/Kitchen',
      durability: 'Medium-High',
      inStockSqFt: 80,
    ),
    const CatalogItem(
      id: '305',
      name: 'Kohler Bathtub',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Bathtub',
      sku: 'SAN-005',
      imageAssetPath: 'assets/images/products/sanitary_bathtub.jpg',
      price: 25000.0,
      material: 'Acrylic',
      origin: 'India',
      finish: 'Glossy White',
      application: 'Bathroom',
      durability: 'Very High',
      inStockSqFt: 15,
    ),
    const CatalogItem(
      id: '306',
      name: 'Grohe Kitchen Sink',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Sink',
      sku: 'SAN-006',
      imageAssetPath: 'assets/images/products/sanitary_sink.jpg',
      price: 5500.0,
      material: 'Stainless Steel 304',
      origin: 'Germany',
      finish: 'Brushed',
      application: 'Kitchen',
      durability: 'Very High',
      inStockSqFt: 30,
    ),
    const CatalogItem(
      id: '307',
      name: 'Roca Mirror Cabinet',
      categoryId: '3',
      categoryName: 'Sanitary',
      subCategory: 'Cabinet',
      sku: 'SAN-007',
      imageAssetPath: 'assets/images/products/sanitary_cabinet.jpg',
      price: 8500.0,
      material: 'MDF with Mirror',
      origin: 'Spain',
      finish: 'Laminated',
      application: 'Bathroom',
      durability: 'Medium',
      inStockSqFt: 25,
    ),

    // CPVC Category (7 items)
    const CatalogItem(
      id: '401',
      name: 'CPVC Pipe 1/2 inch',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Pipe',
      sku: 'CPV-001',
      imageAssetPath: 'assets/images/products/cpvc_pipe_half.jpg',
      price: 180.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Hot/Cold Water Supply',
      durability: 'High (50+ years)',
      inStockSqFt: 250,
    ),
    const CatalogItem(
      id: '402',
      name: 'CPVC Pipe 3/4 inch',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Pipe',
      sku: 'CPV-002',
      imageAssetPath: 'assets/images/products/cpvc_pipe_three_quarter.jpg',
      price: 220.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Hot/Cold Water Supply',
      durability: 'High (50+ years)',
      inStockSqFt: 220,
    ),
    const CatalogItem(
      id: '403',
      name: 'CPVC Elbow 90°',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Fitting',
      sku: 'CPV-003',
      imageAssetPath: 'assets/images/products/cpvc_elbow.jpg',
      price: 25.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Pipe Connections',
      durability: 'High',
      inStockSqFt: 500,
    ),
    const CatalogItem(
      id: '404',
      name: 'CPVC Tee Joint',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Fitting',
      sku: 'CPV-004',
      imageAssetPath: 'assets/images/products/cpvc_tee.jpg',
      price: 30.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Pipe Connections',
      durability: 'High',
      inStockSqFt: 450,
    ),
    const CatalogItem(
      id: '405',
      name: 'CPVC Coupler',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Fitting',
      sku: 'CPV-005',
      imageAssetPath: 'assets/images/products/cpvc_coupler.jpg',
      price: 20.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Pipe Joining',
      durability: 'High',
      inStockSqFt: 600,
    ),
    const CatalogItem(
      id: '406',
      name: 'CPVC Ball Valve',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Valve',
      sku: 'CPV-006',
      imageAssetPath: 'assets/images/products/cpvc_valve.jpg',
      price: 120.0,
      material: 'CPVC with Brass Core',
      origin: 'India',
      finish: 'Standard',
      application: 'Water Flow Control',
      durability: 'Very High',
      inStockSqFt: 180,
    ),
    const CatalogItem(
      id: '407',
      name: 'CPVC End Cap',
      categoryId: '4',
      categoryName: 'CPVC',
      subCategory: 'Fitting',
      sku: 'CPV-007',
      imageAssetPath: 'assets/images/products/cpvc_cap.jpg',
      price: 15.0,
      material: 'CPVC',
      origin: 'India',
      finish: 'Standard',
      application: 'Pipe Closing',
      durability: 'High',
      inStockSqFt: 700,
    ),

    // Ply Category (7 items)
    const CatalogItem(
      id: '501',
      name: 'Marine Plywood 18mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Marine Grade',
      sku: 'PLY-001',
      imageAssetPath: 'assets/images/products/ply_marine.jpg',
      price: 2800.0,
      material: 'Hardwood',
      origin: 'India',
      finish: 'Sanded',
      application: 'Outdoor/Marine Use',
      durability: 'Very High (Waterproof)',
      inStockSqFt: 360,
    ),
    const CatalogItem(
      id: '502',
      name: 'BWR Plywood 12mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Water Resistant',
      sku: 'PLY-002',
      imageAssetPath: 'assets/images/products/ply_bwr.jpg',
      price: 1800.0,
      material: 'Hardwood',
      origin: 'India',
      finish: 'Sanded',
      application: 'Kitchen/Bathroom',
      durability: 'High (Boiling Water Resistant)',
      inStockSqFt: 480,
    ),
    const CatalogItem(
      id: '503',
      name: 'Commercial Ply 6mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Commercial',
      sku: 'PLY-003',
      imageAssetPath: 'assets/images/products/ply_commercial.jpg',
      price: 950.0,
      material: 'Mixed Wood',
      origin: 'India',
      finish: 'Standard',
      application: 'General Purpose',
      durability: 'Medium',
      inStockSqFt: 600,
    ),
    const CatalogItem(
      id: '504',
      name: 'Flexible Plywood 4mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Flexible',
      sku: 'PLY-004',
      imageAssetPath: 'assets/images/products/ply_flexible.jpg',
      price: 1200.0,
      material: 'Softwood',
      origin: 'India',
      finish: 'Sanded',
      application: 'Curved Surfaces',
      durability: 'Medium',
      inStockSqFt: 400,
    ),
    const CatalogItem(
      id: '505',
      name: 'Fireproof Ply 18mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Fire Resistant',
      sku: 'PLY-005',
      imageAssetPath: 'assets/images/products/ply_fireproof.jpg',
      price: 3200.0,
      material: 'Hardwood (FR Grade)',
      origin: 'India',
      finish: 'Sanded',
      application: 'Commercial Buildings',
      durability: 'Very High (Fire Rated)',
      inStockSqFt: 300,
    ),
    const CatalogItem(
      id: '506',
      name: 'Waterproof Ply 12mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Waterproof',
      sku: 'PLY-006',
      imageAssetPath: 'assets/images/products/ply_waterproof.jpg',
      price: 2200.0,
      material: 'Hardwood',
      origin: 'India',
      finish: 'Sanded',
      application: 'Wet Areas',
      durability: 'High (100% Waterproof)',
      inStockSqFt: 440,
    ),
    const CatalogItem(
      id: '507',
      name: 'Shuttering Ply 12mm',
      categoryId: '5',
      categoryName: 'Ply',
      subCategory: 'Shuttering',
      sku: 'PLY-007',
      imageAssetPath: 'assets/images/products/ply_shuttering.jpg',
      price: 1600.0,
      material: 'Mixed Wood',
      origin: 'India',
      finish: 'Standard',
      application: 'Construction Formwork',
      durability: 'Medium-High',
      inStockSqFt: 520,
    ),
  ];
}
